### PR TITLE
support VIRTUAL_IP env variable

### PR DESCRIPTION
**Pull request by unity**
Allowing to manually declare which IP to bind to via `VIRTUAL_IP` env variable. Useful for containers in `network_mode: host`

### CODE REVIEW

**Comment by Gibby** [comment]
+1

**Comment by YanzheL** [comment]
This PR solves #1270 perfectly, Looking forward to seeing this be merged.

**Comment by menaceone** [comment]
hey, very useful feature.
Is there any need for further testing or so?
Would really like to see this merged into master.

**Comment by speedmann** [comment]
any update? It's almost half a year...

**Comment by YanzheL** [comment]
Could you look at this? It's really useful, and we need it too. @jwilder

**Comment by soraxas** [comment]
Please merge thanks

**Comment by mzaborin** [comment]
Please merge

**Comment by Gibby** [comment]
Can't wait for this one. Forked for now(Well 9 months ago, now). Came to check on to see if merged yet and I guess not. 

If anyone needs this I forked on github and linked to docker hub. 
`docker pull gibby/nginx-proxy`

**Comment by perara** [comment]
+1 Merge!

**Comment by cerw** [comment]
Please can we get this marged?

**Comment by gador** [comment]
I'd very much like to see this merged!

**Comment by buchdag** [comment]
PR too old to be workable, if the intended use was to proxy to containers that use `network_mode: host` / `--net=host`, please see #2222

**Pull request closed without merging**
