### PR TITLE
Add ARM builds for running on Raspberry PI

### PR DESCRIPTION
**Pull request by NZSmartie**
This PR does two things.

1. Use `ddollar/forego` as arm binaries available and builds with latest Golang 1.9.
1. Adds `Dockerfile.arm` for building ARM container images for use on a raspberry pi

### CODE REVIEW

**Comment by phikai** [comment]
Any updates on using this as a viable path forward for ARM Builds?

**Comment by rriemann** [comment]
any reason why this is not merged?

I got some warnings due to the fact I'm running on an ARM server.

> standard_init_linux.go:190: exec user process caused "exec format error"

**Comment by jeroenhendricksen** [comment]
I'd love to see support for ARM builds added

**Comment by louismartin** [comment]
Same for me, any reason why it is not merged?

**Comment by SimonLammer** [comment]
I would really appreciate it if this gets merged, as I get `standard_init_linux.go:207: exec user process caused "exec format error"` when using the normal alpine image.

**Comment by biodrone** [comment]
For those who find this after the fact, the forgo pull URL has changed (taken from the Download link in README.MD in https://github.com/ddollar/forego) https://bin.equinox.io/c/ekMN3bCZFUn/forego-stable-linux-arm.tgz

**Comment by VincentCATILLON** [comment]
@jwilder wake up

**Comment by kevinelliott** [comment]
What's the status of this?

**Comment by guysoft** [comment]
Hey guys, also want this. found there is a maintainer actually updating this at:
https://hub.docker.com/r/btcpayserver/docker-gen

Perhaps we should maintain our own version of this.

**Comment by danywheeler** [comment]
any update on this? I also need this.

**Comment by guysoft** [comment]
I used nginx from dockerhub with has arm support, and 3 containers working together:
```
    image: nginx
    image: btcpayserver/docker-gen:0.7.6
    image: duch/letsencrypt-nginx-proxy-companion:stable
```
This lets you run nginx-proxy on arm.

**Comment by Akany** [comment]
Up, can we have it.

**Comment by buchdag** [comment]
Closed in favor of #1470 approach.

**Pull request closed without merging**
