### PR TITLE
Add acme.sh to support automatic letsencrypt ssl cert

### PR DESCRIPTION
**Pull request by Neilpang**
Add a new env variable `ENABLE_ACME=true`

When set to `true`, it will generate free ssl cert from letsencrypt and renew automatically.

### CODE REVIEW

**Comment by Neilpang** [comment]
@jwilder 
Is there any problem with this PR ?

**Comment by buchdag** [comment]
That's a lot of minor / fix / typo / revert commits, you should try to squash them down a bit.

**Comment by Jan0707** [comment]
Is this branch dead ? I'd really like the feature and would hate to see this work fade into nothingness. If @Neilpang can't attend to it, I'd open another one and squash the commits, if that's ok.

**Comment by haemse** [comment]
I vote for it! SSL Cert automation is real convenience esp for this rev proxy solution.

It will make the project much more usable and therefore much more known ..

**Comment by jwilder** [comment]
Let's Encrypt support already exists via https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion.  It also supports the more secure separate containers deployment model which I'm not sure if this PR works with or not.

Is there an issue with using the companion container approach?

**Comment by Neilpang** [comment]
@jwilder 
I knew  the the other project.
but this PR is just more lightweighted,  and it requires little modification of the current configs.

If one is using `jwilder/nginx-proxy` image,   he never never wants to switch to another image just for free ssl certificate.  It's too risky.

This PR almost affects little of the current configs, it works out-of-box.

I have many docker nodes, which are running my own fork `neilpang/nginx-proxy`,  they all are working we for months.

**Comment by Neilpang** [comment]
>> It also supports the more secure separate containers deployment model which I'm not sure if this PR works with or not.

It depends on the base image,  this PR is only lightweighted for ssl stuffs.

As my an other PR https://github.com/jwilder/nginx-proxy/pull/849 (merged already),  as long as this container is running as `host` network,  it can proxy all the containers on the machine.

**Comment by Neilpang** [comment]
@jwilder 
If you think the history of this PR is a mess,  I can send a new one.

Thanks.

**Comment by Jan0707** [comment]
@Neilpang If I am mistaken, correct me, but isn't the major difference, that your PR supports cert creation, whereas the other ones only support cert renewal ?

**Comment by rakshazi** [comment]
Hello!
This is really must-have feature. It's useful for small projects, startups, etc.

**Comment by rakshazi** [comment]
Hello,
Any update on this?

**Comment by rakshazi** [comment]
hi @Neilpang
Please, add both cert create and renew operations

hi @jwilder 
Will you merge this PR if it will be updated and support both cert create and renew?

**Comment by endersonmaia** [comment]
Another point that need to be considered is that, acme.sh supports generation of certificates using DNS entries, and this could enable generating certificates for internal services.

I know that this PR doesn't includes this, but after merged, with some minor enhancements it could be enabled.

**Pull request closed without merging**
