### PR TITLE
fix: Don't error if `$globals.CurrentContainer` is `nil`

### LINKED ISSUE #2189: template nginx.tmpl error : nil pointer evaluating interface {}.Networks
Hello,

I got the following error:
` Template error: template: nginx.tmpl:24:39: executing "nginx.tmpl" at <$globals.CurrentContainer.Networks>: nil pointer evaluating interface {}.Networks`

The nginx.tmpl is https://github.com/nginx-proxy/nginx-proxy/blob/main/nginx.tmpl

my docker-compose.yml is :
```
version: '3.9'

services:
  portail:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "10"
    volumes:
      - porte_conf:/etc/nginx/conf.d:ro
      - porte_htpasswd:/etc/nginx/htpasswd:ro
      - porte_vhost:/etc/nginx/vhost.d:ro
      - porte_html:/usr/share/nginx/html:ro
      - certif_certs:/etc/nginx/certs:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - net-front
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: 'true'

  docker-gen:
    image: nginxproxy/docker-gen:0.10.1
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "10"
    depends_on:
      - portail
    container_name: portail_gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certif_certs:/etc/nginx/certs:ro
      - porte_conf:/etc/nginx/conf.d:rw
      - porte_html:/usr/share/nginx/html:rw
      - porte_htpasswd:/etc/nginx/htpasswd:rw
      - porte_templates:/etc/docker-gen/templates:ro
      - porte_vhost:/etc/nginx/vhost.d:rw
    command: -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen: 'true'
    networks:
      - net-front

  certif:
    image: nginxproxy/acme-companion:2.2.6
    container_name: portail_certif
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "10"
    depends_on:
      - docker-gen
    volumes:
      - certif_certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - porte_conf:/etc/nginx/conf.d
      - porte_vhost:/etc/nginx/vhost.d
      - porte_html:/usr/share/nginx/html
    networks:
      - net-front
    environment:
      NGINX_PROXY_CONTAINER: 'nginx'
      NGINX_DOCKER_GEN_CONTAINER: 'portail_gen'
      DEBUG: 'false'
  vim:
    image: disp/vim
    volumes:
      - porte_conf:/etc/nginx/conf.d:rw
      - porte_html:/usr/share/nginx/html:rw
      - porte_htpasswd:/etc/nginx/htpasswd:rw
      - porte_templates:/etc/docker-gen/templates:rw
      - porte_vhost:/etc/nginx/vhost.d:rw

networks:
  net-front:
    external:
      name: net-proxy

volumes:
  certif_certs:
  porte_conf:
  porte_html:
  porte_htpasswd:
  porte_templates:
  porte_vhost:
```
```
docker version
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:47:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:47:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

And I run the following container :
`docker run --env VIRTUAL_HOST=test.example.com --env VIRTUAL_PORT=8000 --env LETSENCRYPT_HOST=test.example.com --env WWW='no-www' --network=net-proxy jwilder/whoami`

Could you tell me why this error please ?

### PR DESCRIPTION
**Pull request by rhansen**
Also:
  * Note when there are no networks.
  * Fix "networks available" comment.

Fixes #2189

### CODE REVIEW

**Comment by rhansen** [comment]
Can you test this @genestouxguy (or @SchoNie)?

**Comment by SchoNie** [comment]
It's failing for me with -only-exposed:
`Template error: template: nginx.tmpl:29:10: executing "nginx.tmpl" at <sortObjectsByKeysAsc (or $globals.CurrentContainer (dict)).Networks "Name">: error calling sortObjectsByKeysAsc: must pass an array or slice to 'sortObjsByKeys'; received <nil>; kind invalid`

**Comment by rhansen** [comment]
> It's failing for me with -only-exposed

That's what I get for hastily tossing the fix together.  Thanks for testing @SchoNie.  I pushed a new version; would you mind testing it?

**Comment by SchoNie** [comment]
Confirm now it's OK.
Both scenarios (with and without -only-exposed) tested.

**Review by buchdag — APPROVED** [review]

**Pull request merged**
