### PR TITLE
Upgrade Nginx to 1.19.4

### PR DESCRIPTION
**Pull request by lemker**
Upgrade image to latest Nginx release. View changes [here](https://nginx.org/en/CHANGES).

### CODE REVIEW

**Comment by mvthul** [comment]
Last changes on Docker Hub is 9 months ago just to say i wanna try out the new version!

**Comment by mvthul** [comment]
Still getting nginx version 1.17.6 atm
image

**Comment by alekna** [comment]
Duplicated by #1578

**Comment by buchdag** [comment]
Finally superseded by #1590

**Pull request closed without merging**
