### PR TITLE
add proxy header "X-Forwarded-Host"

### PR DESCRIPTION
**Pull request by xujif**
add a proxy header "X-Forwarded-Host".

------
I don't think it's a good idea to trust any external proxy with X-Forwarded-* headers.

### CODE REVIEW

**Comment by xujif** [comment]
For security reasons, I think these configurations should be set to `
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Proto $scheme;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";

`

**Comment by buchdag** [comment]
Hi.

Could you elaborate on what this PR does and the security reasons that motivate those changes ? I'm not fluent enough in nginx to get it straight away.

**Comment by rhansen** [comment]
@xujif @buchdag See PR #1927.

**Comment by rhansen** [comment]
> Could you elaborate on what this PR does

@buchdag This PR sets the `X-Forwarded-Host` header to the value of the client-supplied `Host` header (or the value of the client-supplied `X-Forwarded-Host` header, if present) when forwarding the request to the backend server. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host for why some backend servers find this header to be useful.

> and the security reasons that motivate those changes ?

The [comment](https://github.com/nginx-proxy/nginx-proxy/pull/1836#issuecomment-990624010) by @xujif is regarding a somewhat separate topic: the security implications of trusting client-supplied headers. That is best addressed in a separate PR (see #1927), but it was mentioned here because this PR follows the same dangerous pattern already established for the `X-Forwarded-Proto` and `X-Forwarded-Port` headers for consistency.

**Comment by rhansen** [comment]
Tests:

```diff
diff --git a/test/test_headers/test_http.py b/test/test_headers/test_http.py
index 5983a10..739b455 100644
--- a/test/test_headers/test_http.py
+++ b/test/test_headers/test_http.py
@@ -30,6 +30,19 @@ def test_X_Forwarded_Proto_is_passed_on(docker_compose, nginxproxy):
     assert "X-Forwarded-Proto: f00\n" in r.text
 
 
+##### Testing the handling of X-Forwarded-Host #####
+
+def test_X_Forwarded_Host_is_generated(docker_compose, nginxproxy):
+    r = nginxproxy.get("http://web.nginx-proxy.tld/headers")
+    assert r.status_code == 200
+    assert "X-Forwarded-Host: web.nginx-proxy.tld\n" in r.text
+
+def test_X_Forwarded_Host_is_passed_on(docker_compose, nginxproxy):
+    r = nginxproxy.get("http://web.nginx-proxy.tld/headers", headers={'X-Forwarded-Host': 'example.com'})
+    assert r.status_code == 200
+    assert "X-Forwarded-Host: example.com\n" in r.text
+
+
 ##### Testing the handling of X-Forwarded-Port #####
 
 def test_X_Forwarded_Port_is_generated(docker_compose, nginxproxy):
diff --git a/test/test_headers/test_https.py b/test/test_headers/test_https.py
index c5457c4..7a428ae 100644
--- a/test/test_headers/test_https.py
+++ b/test/test_headers/test_https.py
@@ -33,6 +33,19 @@ def test_X_Forwarded_Proto_is_passed_on(docker_compose, nginxproxy):
     assert "X-Forwarded-Proto: f00\n" in r.text
 
 
+##### Testing the handling of X-Forwarded-Host #####
+
+def test_X_Forwarded_Host_is_generated(docker_compose, nginxproxy):
+    r = nginxproxy.get("https://web.nginx-proxy.tld/headers")
+    assert r.status_code == 200
+    assert "X-Forwarded-Host: web.nginx-proxy.tld\n" in r.text
+
+def test_X_Forwarded_Host_is_passed_on(docker_compose, nginxproxy):
+    r = nginxproxy.get("https://web.nginx-proxy.tld/headers", headers={'X-Forwarded-Host': 'example.com'})
+    assert r.status_code == 200
+    assert "X-Forwarded-Host: example.com\n" in r.text
+
+
 ##### Testing the handling of X-Forwarded-Port #####
 
 def test_X_Forwarded_Port_is_generated(docker_compose, nginxproxy):
```

**Comment by buchdag** [comment]
@rhansen this PR would be superseded by #1927, right ?

**Comment by rhansen** [comment]
PR #1927 alters the behavior of the existing `X-Forwarded-Proto`, `X-Forwarded-Ssl`, and `X-Forwarded-Port` headers while this PR adds a new `X-Forwarded-Host` header.

Whichever of these two PRs is merged first, the other will have to be adjusted to include the new `X-Forwarded-Host` header in the set of headers covered by `TRUST_DOWNSTREAM_PROXY`.

**Review by SilverFire — APPROVED** [review]

**Comment by SilverFire** [comment]
Supporting this idea

**Comment by buchdag** [comment]
@rhansen any preference on merging this PR first then #1927 or the inverse ?

**Comment by buchdag** [comment]
@rhansen #1927 is finally merged if you still want to take a look at this one.

**Comment by rhansen** [comment]
> @rhansen #1927 is finally merged if you still want to take a look at this one.

Thanks!  I opened #2121, which supersedes this PR.

**Comment by buchdag** [comment]
Closed in favor of #2121

**Pull request closed without merging**
