### PR TITLE
Set DISABLE_ACCESS_LOGS env var to disable access logs

### PR DESCRIPTION
**Pull request by basro**
This PR removes the access_log lines from the generated nginx config if DISABLE_ACCESS_LOGS env var is set in the nginx-proxy container.

I think this would solve issue #503

### CODE REVIEW

**Comment by Fohlen** [comment]
Can this be brought forward @jwilder? It is also a nice way to disable the default logging for an alternate logging format, thus making it possible to comply with the DGPR that's coming soon 👍

**Comment by krivochenko** [comment]
I am also interested in these changes, because there are containers for which I do not want to log requests.

**Comment by Slayer911** [comment]
good idea, but for a year there has been no solution

**Comment by tjhiggins** [comment]
+1

**Comment by tjhiggins** [comment]
@jwilder Thank you - that was amazing! How often do you update the docker tag?

**Comment by gaastonsr** [comment]
Agreed, this is awesome, I would appreciate an updated image 🙏🏽. Thanks

**Comment by modmoto** [comment]
would totally like to update to this version aswell =D

**Comment by throny** [comment]
As this is already merged to the master branch, when will it be included in a new image?
Tried setting the env var in the desired container and in the nginx-container itself: neither does work. Would really love this feature!

**Comment by tkw1536** [comment]
This should be available on the main branch and current images since [0.8.0](https://github.com/nginx-proxy/nginx-proxy/releases/tag/0.8.0). 

@throny  Can you try setting `DISABLE_ACCESS_LOGS=1` (as opposed to without a value)?

**Comment by throny** [comment]
That did the trick! Thank you @tkw1536 ! 
However it only works for the nginx-container itself, not for the docker containers behind the proxy right?

**Comment by tkw1536** [comment]
Correct, `nginx-proxy` cannot influence logging behavior of other docker containers.

**Pull request merged**
