### PR TITLE
Use `server 127.0.0.1 down` entry only when required

### PR DESCRIPTION
**Pull request by pini-gh**
See https://github.com/nginx-proxy/nginx-proxy/pull/1609#issuecomment-858150285.

Additionally, fix a warning due to a missing backslash escaping from previous merge request.

### CODE REVIEW

**Comment by buchdag** [comment]
Do you think the test cases could be expanded to include the following:

- multiple (three ?) containers with the same `VIRTUAL_HOST`, one on an unreachable network: assert that we still don't get `server 127.0.0.1 down` in this setup
- single container with multiple unreachable networks (I don't know if it's possible): assert that we only get `server 127.0.0.1 down` once

Or maybe it's overkill ?

Excellent work anyway, thank you.

**Comment by pini-gh** [comment]
>     * multiple (three ?) containers with the same `VIRTUAL_HOST`, one on an unreachable network: assert that we still don't get `server 127.0.0.1 down` in this setup
This implies that they use the same VIRTUAL_PORT, doesn't it?

>     * single container with multiple unreachable networks (I don't know if it's possible): assert that we only get `server 127.0.0.1 down` once
Will give it a try.

**Comment by buchdag** [comment]
> This implies that they use the same VIRTUAL_PORT, doesn't it?

Not necessarily. The idea was to cover the (undocumented, admittedly) use case of people doing load balancing behind nginx-proxy as described in #1654, but failing this test won't mean that this use case would stop working. Both this test and the other one are more unit testing than functional testing, hence the overkill question.

I have no problem merging this now and adding further tests later of you agree that they'd be nice to have.

**Comment by pini-gh** [comment]
> single container with multiple unreachable networks (I don't know if it's possible): assert that we only get `server 127.0.0.1 down` once

@buchdag I don't know how to do it using docker-compose v1 syntax. And and my box `test_composev2` fails because `test_nginx-proxy_1` and `test_web_1` are on the auto allocated `test_default` network while the `nginx-proxy-tester` instance is on the `bridge` network. Then the tester can't talk to the usecase instances. Any idea?

**Pull request merged**
