### PR TITLE
added VIRTUAL_PATH support

### PR DESCRIPTION
**Pull request by sfussenegger**
this is loosely based on #254 but using the latest master. it supports multiple `VIRTUAL_HOST` per container and in general and any number of `VIRTUAL_PATH` per server.

This PR probably isn't going to make it into master but I still wanted to submit it. Maybe somebody can use it anyway.

### CODE REVIEW

**Comment by SergioRius** [comment]
Thanks for your work.

Can I ask you how to use the env variables to redirect docker services on a local server without dns?
like: `192.168.1.1/monit`
I'm creating the following ones but still get a 503 err:
```
VIRTUAL_HOST=localhost   (and 127.0.0.1)
VIRTUAL_PATH=/monit
```
Thanks again.

**Comment by bmmathe** [comment]
Please merge this PR.  So useful out-of-box support for virtual paths.  Until it's merged I will hack together my own container from the OP branch.

**Comment by CReimer** [comment]
+1

**Comment by h45rd** [comment]
Working great in my testing environment.
Any additional testing or help needed to get this merged into master?

**Comment by buchdag** [comment]
This features has been added to the `dev` branch with #1607 

It's available now on the `dev` images `nginxproxy/nginx-proxy:dev` and `nginxproxy/nginx-proxy:dev-alpine`. Testing and feedback are welcome, the docs for the feature is [here](https://github.com/nginx-proxy/nginx-proxy/tree/dev#path-based-routing) and there is [another PR](https://github.com/nginx-proxy/nginx-proxy/pull/1699) opened for additional improvements and comments.

**Pull request closed without merging**
